version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node-browsers
    steps:
      - checkout
      - run: npm install
      - run: bundle install
      - run: bundle exec jekyll build
      - run: (cd styleguide && npm install && fractal build)
      - run: sudo apt install python-pip python-dev
      - run: sudo pip install awscli
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync ./_site s3://tspdev.gov/ --delete
            elif [ "${CIRCLE_BRANCH}" = "staging" ]; then
              aws s3 sync ./_site s3://tspstaging.gov/ --delete
            else
              echo "If not staging or master branch, dry run only"
            fi
